### ISSUE TITLE
Be careful of Chandu Vadde

### ISSUE THREAD

**Issue by apliedai** [cyrixninja/EcoTransit#1]
Just want to let you know that Chandu Vadde is code stealer, betrayer and bad influencer for fellow developers. He asked members in team to steal code, defied the rules of hackathons to win. He could join two teams at the same time and be betrayer of the group. He also has history of stealing codes that were developed by the whole team and uploaded it to hackathons for him to win individually. I just saw he forked the code of Codify to his repo. I hope he did tell and get permission of the whole team before doing that. If not, be careful, Chandu is a dangerous person who could do anything to win. He could not attend hackathons by himself because he is not talented that is why he tried to team up with other developers with better skills to win the prizes. His account was reported to Devpost before because of all his wrong doing. Now he is thirsty for money and is trying to steal again to gain monetary prizes.

**Comment by cyrixninja** [comment]
Thanks for bringing this to me. I also had bad experience with him in the past so I didn't collaborate with him again. I completely agree with you. Lemme know if i could be of any help to you.
